<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hiking Activity Report</title>
    <style>
        body { font-family: sans-serif; padding: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .meta { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 12px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .status-active { color: green; font-weight: bold; }
        .status-completed { color: blue; }
        
        /* CSS khusus saat dicetak (Print to PDF) */
        @media print {
            .no-print { display: none; }
            body { padding: 0; }
        }
    </style>
</head>
<body>
    <button class="no-print" onclick="window.print()" style="padding: 10px 20px; background: #333; color: white; cursor: pointer; margin-bottom: 20px;">
        🖨️ Print / Save as PDF
    </button>

    <div class="header">
        <h2>DAILY HIKING ACTIVITY REPORT</h2>
        <p>Mount Papandayan Monitoring System</p>
    </div>

    <div class="meta">
        <strong>Date:</strong> {{ $date }} <br>
        <strong>Generated By:</strong> {{ auth()->user()->name }} (Forestry Officer)
    </div>

    <div style="display: flex; justify-content: space-between; margin-bottom: 20px; background: #f9f9f9; padding: 10px; border: 1px solid #ddd;">
        <div>Total Hikers: <strong>{{ $total_hikers }}</strong></div>
        <div>Active on Trail: <strong>{{ $active_hikers }}</strong></div>
        <div>Completed Today: <strong>{{ $completed_hikers }}</strong></div>
    </div>

    <h3>Recent Activity Logs</h3>
    <table>
        <thead>
            <tr>
                <th>Time</th>
                <th>Reg ID</th>
                <th>Hiker Name</th>
                <th>Last Position</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($recent_hikes as $hike)
            <tr>
                <td>{{ $hike->created_at->format('H:i') }}</td>
                <td>{{ $hike->hike_registration_id }}</td>
                <td>{{ $hike->user->name }}</td>
                <td>
                    {{ $hike->lastLog ? $hike->lastLog->checkpoint->name : 'Basecamp' }}
                    <small style="color:gray">({{ $hike->updated_at->diffForHumans() }})</small>
                </td>
                <td class="{{ $hike->status == 'active' ? 'status-active' : 'status-completed' }}">
                    {{ ucfirst($hike->status) }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div style="margin-top: 50px; text-align: right;">
        <p>Authorized Signature,</p>
        <br><br><br>
        <p>__________________________</p>
        <p>Forestry Dept. Officer</p>
    </div>
</body>
</html>